AllCops:
  Exclude:
    - spec/**/*
    - db/**/*
    - sequel_simple_oauth2.rb

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Metrics/MethodLength:
  Max: 15
Metrics/LineLength:
  Max: 120
Style/Lambda:
  Enabled: false
Style/DotPosition:
  Enabled: false
